name: Build OpenWRT Firmware

on:
  workflow_dispatch:  # 手动触发以控制 Release 创建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
        sudo apt-get update  
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst

      - name: Decompress ImageBuilder
        run: |
          tar -I zstd -xvf immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
          cd immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64

      - name: Copy Custom IPKs
        run: |
          cd immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64
          mkdir -p packages
          cp ../../custom-packages/*.ipk packages/ || true

      - name: Build Firmware
        run: |
          cd immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64
          make image PROFILE="generic" PACKAGES="$(cat ../../packages.txt)" FILES="../../files/" ROOTFS_PARTSIZE=1024

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64/bin/targets/x86/64/*.img.gz

      - name: Release Firmware
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64/bin/targets/x86/64/
          RELEASE_TAG="v$(date +%Y%m%d)"
          # 检查 Release 是否存在
          if gh release view $RELEASE_TAG --repo $GITHUB_REPOSITORY >/dev/null 2>&1; then
            echo "Release $RELEASE_TAG already exists, uploading to existing release."
            gh release upload $RELEASE_TAG *.img.gz --clobber
          else
            echo "Creating new release $RELEASE_TAG."
            gh release create $RELEASE_TAG --title "Firmware Build $RELEASE_TAG" --notes "Automated ImmortalWRT build with custom IPKs and configs."
            gh release upload $RELEASE_TAG *.img.gz
          fi
