name: Build OpenWRT Firmware

on:
  - push
  - workflow_dispatch  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: immortalwrt/imagebuilder:x86-64-openwrt-24.10.2
      options: --user root  # Run as root to avoid permission issues during build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This checks out your repo, where you can store custom config files if needed (e.g., .config or packages list)

      - name: Prepare build environment
        run: |
          # Update any necessary dependencies inside the container if required
          apt-get update && apt-get install -y sudo  # Ensure sudo is available if needed
          # Optionally, copy custom configs from repo to the build dir
          # cp .github/configs/myconfig .config  # Example: If you have a custom .config file in your repo

      - name: Build OpenWRT firmware
        run: |
          # Run the ImageBuilder make command to build the firmware
          # Customize PROFILE and PACKAGES as needed
          # PROFILE: Device profile, e.g., 'generic' for x86-64
          # PACKAGES: List of packages to include, e.g., 'luci luci-app-firewall'
          # FILES: Directory for custom files to include in the image
          make image PROFILE="generic" PACKAGES="luci luci-app-firewall" FILES="files/"
          
          # After build, the output files will be in bin/targets/x86/64/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/x86/64/  # Upload the compiled firmware files
          retention-days: 5  # Keep artifacts for 5 days
